version: 0.2
phases:
  install:
    commands:
      - curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
      - unzip terraform.zip && mv terraform /usr/local/bin/
  build:
    commands:
      - echo "Validating Terraform..."
      - terraform init -backend=false
      - terraform validate
