version: 0.2
phases:
  install:
    commands:
      - curl -s -qL -o terraform.zip
        https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_arm64.zip
      - unzip terraform.zip && mv terraform /usr/local/bin/
      - chmod +x /usr/local/bin/terraform
  build:
    commands:
      - echo "Running Terraform Plan..."
      - terraform init
      - terraform plan -out=tfplan
artifacts:
  files:
    - tfplan
    - .terraform.lock.hcl